### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by francho3** [SantanderMetGroup/downscaleR#34]
Hi Dears,

Some months ago I used downscaleR, to made bias correction for time series obs and wrf outputs, now been updated the new code and found a problems, please can you help me?.

> Macu_bc_obs <-Macu_bc$obs
> Macu_fcst <- Macu_bc$fcst
> 
> y <- Macu_bc$obs
> x <- Macu_fcst
> newdata <- x
> cal.t <- biasCorrection (y, x, newdata = NULL, method = "scaling",
> -                          scaling.type = "additive")
>   Error in obs$Variable : $ operator is invalid for atomic vectors

**Comment by miturbide** [comment]
Dear francho3,

The input objects for applying function biasCorrection are "grids" (lists) (see https://github.com/SantanderMetGroup/loadeR/wiki for more information on data structure). The downscaleR package, and the rest of packages from the same bundle, are  based in the same grid data structure. We highly recommend the use of  grids, because function biasCorrection efficiently computes bias correction to all the series in a grid and also allows applying further methods such as cross validation.

Alternatively, you could apply the internal basic functions of bias correction to work with time series (vectors):

cat.t <- downscaleR::scaling(o = y, p = x, s = newdata, scaling.type = "additive"))

Best,

Maialen
