### ISSUE TITLE
Unable to install downscaleR on Windows7(64 bit)

### ISSUE THREAD

**Issue by javakh** [SantanderMetGroup/downscaleR#4]
Hello,
I'm trying to install downscaleR on Windows 7 (64 bit) and getting the following error:
> library(devtools)
>devtools::install_github(c("SantanderMetGroup/downscaleR.java","SantanderMetGroup/downscaleR"))
Downloading github repo SantanderMetGroup/downscaleR.java@master
Installing downscaleR.java
"C:/PROGRA~1/R/R-31~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/tutul/AppData/Local/Temp/RtmpoloQGb/devtools14c057be6fba/SantanderMetGroup-downscaleR.java-357b9ec" --library="C:/Users/tutul/Documents/R/win-library/3.1"  \
  --install-tests 

* installing *source* package 'downscaleR.java' ...
** R
** inst
** preparing package for lazy loading
Warning: package 'rJava' was built under R version 3.1.3
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning: package 'rJava' was built under R version 3.1.3
*** arch - x64
Warning: package 'rJava' was built under R version 3.1.3
* DONE (downscaleR.java)
Downloading github repo SantanderMetGroup/downscaleR@master
Installing downscaleR
Skipping 1 packages not available: downscaleR.java
"C:/PROGRA~1/R/R-31~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/tutul/AppData/Local/Temp/RtmpoloQGb/devtools14c036d6444c/SantanderMetGroup-downscaleR-0da25a5" --library="C:/Users/tutul/Documents/R/win-library/3.1"  \
  --install-tests 

* installing *source* package 'downscaleR' ...
** R
Error in parse(outFile) : 
  C:/Users/tutul/AppData/Local/Temp/RtmpoloQGb/devtools14c036d6444c/SantanderMetGroup-downscaleR-0da25a5/R/biasCorrection.R:79:1: unexpected input
78: #' 
79: <<
    ^
ERROR: unable to collate and parse R files for package 'downscaleR'
* removing 'C:/Users/tutul/Documents/R/win-library/3.1/downscaleR'
Error: Command failed (1)

How to fix this problem and how can I install this package??

Note that I downscaleR.java have been installed succesfully.

Please help.

**Comment by dianalucatero** [comment]
Hey javakh! Were you able to install it? I have a similar problem but I cannot even install the downscaleR.java package :(.

Help!

**Comment by Yuanchao-Xu** [comment]
@javakh @dianalucatero 

Hi guys,

We just solved the problem on our server, I'm not sure if you have the same problem as we had, just put the solution as reference.

First we located the problem, as our experience, all the problems with package came from java.
So, it was probably the java problem of the computer.

In the installation, you have to set environment variables, adding your java path to your path. I have tried a lot of times installing different versions of java, which didn't work.

Then we thought only reinstall java wouldn't work.

We found a machine, which has downscaleR previously installed. And copy the java folder to our server, put it into different location, and reset environment variables (path) to that location. And it worked.

Anyway, I still think it was by luck that it worked. Because when I set the path back to original, it still worked. So I guess maybe, in the process above, something had solved problem that we didn't know, e.g. path or java_home or something related.

Well I hope that worked to you guys. And if any of you find the real problem, pls contact me, thx.

**Comment by anilsagar651** [comment]
devtools::install_github(c("SantanderMetGroup/downscaleR.java@stable","SantanderMetGroup/downscaleR@stable"))
Downloading GitHub repo SantanderMetGroup/downscaleR.java@stable
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached


I encountered such problem while trying to install downscaleR R package. The version of R used is 3.1.3 in win7 64bit OS. Please could anybody help?

**Comment by jbedia** [comment]
@Yuanchao-Xu Thanks for reporting. In the following link you may find some additional information regarding the java configuration in R: http://meteo.unican.es/trac/wiki/udg/ecoms/RPackage/prerequisites

@anilsagar651 The stable branches are not being used anymore. The latest stable release is now in the master branch, as explained in the README.md. 
I hope this helps
