### ISSUE TITLE
Reference to Themeßl et al. (2012) in the documentation

### ISSUE THREAD

**Issue by huard** [SantanderMetGroup/downscaleR#71]
The dry-day frequency adjustement is documented in `biasCorrection.R` as following Themeßl et al. (2012), but the only reference I could find (DOI: 10.1007/s10584-011-0224-4) uses a uniform distribution instead of a gamma distribution. Is it possible that the reference rather is Hempel et al. (2013) (DOI: 10.5194/esd-4-219-2013) ?

**Comment by miturbide** [comment]
Thank you @huard ,

The documentation has been changed in the devel branch (section Details) as follows:

_"In the case of precipitation a frequency adaptation is performed in all versions of quantile mapping following Themeßl et al. (2012; https://doi.org/10.1007/s10584-011-0224-4), but sampling from the observed Gamma distribution instead of using linear interpolation. This is a preprocess to alleviate the problems arising when the dry day frequency in the raw model output is larger than in the observations. The opposite situation is automatically adjusted by quantile methods."_

We take note to include examples and further details in a future version.
